POST http://localhost:5000/api/notifications
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2Mzk2MTIyODl9.UEnEKsu8ilc8e0uAMM_MRTiiFLiCZtwYNt4Z-ZY8Rrc

{
    "message":"L''etat de votre annonce ''...'' a été changé par ''...''",
    "id_user": 1
}

###

DELETE http://localhost:5000/api/notifications/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2Mzk2MTIyODl9.UEnEKsu8ilc8e0uAMM_MRTiiFLiCZtwYNt4Z-ZY8Rrc

###

PUT http://localhost:5000/api/notifications/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2Mzk2MTIyODl9.UEnEKsu8ilc8e0uAMM_MRTiiFLiCZtwYNt4Z-ZY8Rrc

{
    "isseen": true,
    "message":"L''etat de SASA''...'' a été changé par ''...''",
    "id_user": 1
}

###

GET http://localhost:5000/api/notifications/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF91c2VyIjoxLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2Mzk2MTIyODl9.UEnEKsu8ilc8e0uAMM_MRTiiFLiCZtwYNt4Z-ZY8Rrc