GET http://localhost:5000/api/utilisateurs

###

GET http://localhost:5000/api/utilisateurs/3

###

POST http://localhost:5000/api/utilisateurs
Content-Type: application/json

{
    "email": "jesuisunetomate@gmail.com",
    "last_name": "Mate",
    "first_name": "To",
    "password": "Azerty",
    "campus": "Woluwe",
    "role": "Admin"
}

###

PUT http://localhost:5000/api/utilisateurs/4
Content-Type: application/json

{
    "email": "jesuisunetomate@gmail.com",
    "last_name": "Mate",
    "first_name": "To",
    "password": "Azerty",
    "campus": "Woluwe",
    "role": "Mute"
}

###

DELETE http://localhost:5000/api/utilisateurs/4