GET http://localhost:5000/api/annonces

###

GET http://localhost:5000/api/annonces?categorie=Velos

###

GET http://localhost:5000/api/annonces?tri=DESC

###

GET http://localhost:5000/api/annonces?prixMin=100

###

GET http://localhost:5000/api/annonces?prixMax=100

###

GET http://localhost:5000/api/annonces?prixMin=100&prixMax=100

###

GET http://localhost:5000/api/annonces?categorie=Velos&tri=DESC

###

GET http://localhost:5000/api/annonces?categorie=Velos&prixMin=500

###

GET http://localhost:5000/api/annonces?categorie=Velos&prixMax=100

###

GET http://localhost:5000/api/annonces?categorie=Velos&prixMin=100&prixMax=100

###

GET http://localhost:5000/api/annonces?tri=ASC&prixMin=300

###

GET http://localhost:5000/api/annonces?tri=DESC&prixMax=100

###

GET http://localhost:5000/api/annonces?tri=DESC&prixMin=100&prixMax=100

###

GET http://localhost:5000/api/annonces?categorie=Velos&tri=ASC&prixMin=300

###

GET http://localhost:5000/api/annonces?categorie=Velos&tri=DESC&prixMax=300

###

GET http://localhost:5000/api/annonces?categorie=Velos&tri=ASC&prixMin=500&prixMax=500

### TOKEN ADMIN

GET http://localhost:5000/api/annonces/all
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoxLCJyb2xlIjoiYWRtaW4ifQ.EDHVyMuW-q6qbjR3OrpY_H19wNX6hESwnN4VzbAKUSg

### TOKEN USER 1

GET http://localhost:5000/api/annonces/3
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoxLCJyb2xlIjoidXNlciJ9.5Kz5-0BMKEGQy_PpJqbygyXIYpANsvf6FaPBDadk5Uk

### TOKEN USER 1

POST http://localhost:5000/api/annonces
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoxLCJyb2xlIjoidXNlciJ9.5Kz5-0BMKEGQy_PpJqbygyXIYpANsvf6FaPBDadk5Uk

{
    "title": "Velo",
    "description": "Velo moche",
    "price": 100,
    "date": "07/12/2021",
    "state": "sold",
    "type": "sell",
    "displayed_picture":0,
    "id_user": 14,
    "id_category":1
}

### TOKEN USER 1

PUT http://localhost:5000/api/annonces/50
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoxLCJyb2xlIjoidXNlciJ9.5Kz5-0BMKEGQy_PpJqbygyXIYpANsvf6FaPBDadk5Uk

{
    "title": "Super livre !!",
    "description": "Velo moche",
    "price": 100,
    "date": "07/12/2021",
    "state": "available",
    "type": "sell",
    "displayed_picture":0,
    "id_user": 14,
    "id_category":2
}


### TOKEN USER 1

DELETE http://localhost:5000/api/annonces/6
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoxLCJyb2xlIjoidXNlciJ9.5Kz5-0BMKEGQy_PpJqbygyXIYpANsvf6FaPBDadk5Uk