GET http://localhost:5000/api/users

###

POST http://localhost:5000/api/user
Content-Type: application/json

{
    "email": "jesuisunetomate@gmail.com",
    "last_name": "Mate",
    "first_name": "To",
    "password": "Azerty",
    "campus": "Woluwe",
    "isAdmin": true,
    "isBanned": false
}

###

PUT http://localhost:5000/api/utilisateurs/1